package askr.entity;

import java.math.BigDecimal;
import java.util.Date;

public class StockTransactionDataList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_transaction_data_list.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_transaction_data_list.stock_code
     *
     * @mbg.generated
     */
    private String stockCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_transaction_data_list.trade
     *
     * @mbg.generated
     */
    private BigDecimal trade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_transaction_data_list.pricechange
     *
     * @mbg.generated
     */
    private BigDecimal pricechange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_transaction_data_list.changepercent
     *
     * @mbg.generated
     */
    private BigDecimal changepercent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_transaction_data_list.buy
     *
     * @mbg.generated
     */
    private BigDecimal buy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_transaction_data_list.sell
     *
     * @mbg.generated
     */
    private BigDecimal sell;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_transaction_data_list.settlement
     *
     * @mbg.generated
     */
    private BigDecimal settlement;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_transaction_data_list.open
     *
     * @mbg.generated
     */
    private BigDecimal open;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_transaction_data_list.high
     *
     * @mbg.generated
     */
    private BigDecimal high;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_transaction_data_list.low
     *
     * @mbg.generated
     */
    private BigDecimal low;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_transaction_data_list.volume
     *
     * @mbg.generated
     */
    private Long volume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_transaction_data_list.amount
     *
     * @mbg.generated
     */
    private Long amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_transaction_data_list.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_transaction_data_list.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_transaction_data_list.id
     *
     * @return the value of stock_transaction_data_list.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_transaction_data_list.id
     *
     * @param id the value for stock_transaction_data_list.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_transaction_data_list.stock_code
     *
     * @return the value of stock_transaction_data_list.stock_code
     *
     * @mbg.generated
     */
    public String getStockCode() {
        return stockCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_transaction_data_list.stock_code
     *
     * @param stockCode the value for stock_transaction_data_list.stock_code
     *
     * @mbg.generated
     */
    public void setStockCode(String stockCode) {
        this.stockCode = stockCode == null ? null : stockCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_transaction_data_list.trade
     *
     * @return the value of stock_transaction_data_list.trade
     *
     * @mbg.generated
     */
    public BigDecimal getTrade() {
        return trade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_transaction_data_list.trade
     *
     * @param trade the value for stock_transaction_data_list.trade
     *
     * @mbg.generated
     */
    public void setTrade(BigDecimal trade) {
        this.trade = trade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_transaction_data_list.pricechange
     *
     * @return the value of stock_transaction_data_list.pricechange
     *
     * @mbg.generated
     */
    public BigDecimal getPricechange() {
        return pricechange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_transaction_data_list.pricechange
     *
     * @param pricechange the value for stock_transaction_data_list.pricechange
     *
     * @mbg.generated
     */
    public void setPricechange(BigDecimal pricechange) {
        this.pricechange = pricechange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_transaction_data_list.changepercent
     *
     * @return the value of stock_transaction_data_list.changepercent
     *
     * @mbg.generated
     */
    public BigDecimal getChangepercent() {
        return changepercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_transaction_data_list.changepercent
     *
     * @param changepercent the value for stock_transaction_data_list.changepercent
     *
     * @mbg.generated
     */
    public void setChangepercent(BigDecimal changepercent) {
        this.changepercent = changepercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_transaction_data_list.buy
     *
     * @return the value of stock_transaction_data_list.buy
     *
     * @mbg.generated
     */
    public BigDecimal getBuy() {
        return buy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_transaction_data_list.buy
     *
     * @param buy the value for stock_transaction_data_list.buy
     *
     * @mbg.generated
     */
    public void setBuy(BigDecimal buy) {
        this.buy = buy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_transaction_data_list.sell
     *
     * @return the value of stock_transaction_data_list.sell
     *
     * @mbg.generated
     */
    public BigDecimal getSell() {
        return sell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_transaction_data_list.sell
     *
     * @param sell the value for stock_transaction_data_list.sell
     *
     * @mbg.generated
     */
    public void setSell(BigDecimal sell) {
        this.sell = sell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_transaction_data_list.settlement
     *
     * @return the value of stock_transaction_data_list.settlement
     *
     * @mbg.generated
     */
    public BigDecimal getSettlement() {
        return settlement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_transaction_data_list.settlement
     *
     * @param settlement the value for stock_transaction_data_list.settlement
     *
     * @mbg.generated
     */
    public void setSettlement(BigDecimal settlement) {
        this.settlement = settlement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_transaction_data_list.open
     *
     * @return the value of stock_transaction_data_list.open
     *
     * @mbg.generated
     */
    public BigDecimal getOpen() {
        return open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_transaction_data_list.open
     *
     * @param open the value for stock_transaction_data_list.open
     *
     * @mbg.generated
     */
    public void setOpen(BigDecimal open) {
        this.open = open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_transaction_data_list.high
     *
     * @return the value of stock_transaction_data_list.high
     *
     * @mbg.generated
     */
    public BigDecimal getHigh() {
        return high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_transaction_data_list.high
     *
     * @param high the value for stock_transaction_data_list.high
     *
     * @mbg.generated
     */
    public void setHigh(BigDecimal high) {
        this.high = high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_transaction_data_list.low
     *
     * @return the value of stock_transaction_data_list.low
     *
     * @mbg.generated
     */
    public BigDecimal getLow() {
        return low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_transaction_data_list.low
     *
     * @param low the value for stock_transaction_data_list.low
     *
     * @mbg.generated
     */
    public void setLow(BigDecimal low) {
        this.low = low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_transaction_data_list.volume
     *
     * @return the value of stock_transaction_data_list.volume
     *
     * @mbg.generated
     */
    public Long getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_transaction_data_list.volume
     *
     * @param volume the value for stock_transaction_data_list.volume
     *
     * @mbg.generated
     */
    public void setVolume(Long volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_transaction_data_list.amount
     *
     * @return the value of stock_transaction_data_list.amount
     *
     * @mbg.generated
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_transaction_data_list.amount
     *
     * @param amount the value for stock_transaction_data_list.amount
     *
     * @mbg.generated
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_transaction_data_list.created_at
     *
     * @return the value of stock_transaction_data_list.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_transaction_data_list.created_at
     *
     * @param createdAt the value for stock_transaction_data_list.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_transaction_data_list.updated_at
     *
     * @return the value of stock_transaction_data_list.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_transaction_data_list.updated_at
     *
     * @param updatedAt the value for stock_transaction_data_list.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}