package askr.entity;

import java.util.Date;

public class StockCodeList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_code_list.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_code_list.stock_code
     *
     * @mbg.generated
     */
    private String stockCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_code_list.stock_name
     *
     * @mbg.generated
     */
    private String stockName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_code_list.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_code_list.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_code_list.id
     *
     * @return the value of stock_code_list.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_code_list.id
     *
     * @param id the value for stock_code_list.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_code_list.stock_code
     *
     * @return the value of stock_code_list.stock_code
     *
     * @mbg.generated
     */
    public String getStockCode() {
        return stockCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_code_list.stock_code
     *
     * @param stockCode the value for stock_code_list.stock_code
     *
     * @mbg.generated
     */
    public void setStockCode(String stockCode) {
        this.stockCode = stockCode == null ? null : stockCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_code_list.stock_name
     *
     * @return the value of stock_code_list.stock_name
     *
     * @mbg.generated
     */
    public String getStockName() {
        return stockName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_code_list.stock_name
     *
     * @param stockName the value for stock_code_list.stock_name
     *
     * @mbg.generated
     */
    public void setStockName(String stockName) {
        this.stockName = stockName == null ? null : stockName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_code_list.created_at
     *
     * @return the value of stock_code_list.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_code_list.created_at
     *
     * @param createdAt the value for stock_code_list.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_code_list.updated_at
     *
     * @return the value of stock_code_list.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_code_list.updated_at
     *
     * @param updatedAt the value for stock_code_list.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}